### ISSUE TITLE
Feature Request: yoda summon

### ISSUE THREAD

**Issue by jvendryes** [kcmerrill/yoda#12]
When I do “yoda summon something/something” it would be neat to have a flag that could automatically create a folder I specify instead of having to move it after the summon. This is especially useful for "bootstrap" style containers where its a base web server only.

For example, something like:
`yoda summon something/something <myfolder>`

This would summon into <myfolder> rather than into a folder called "something".

**Comment by kcmerrill** [comment]
You can do this by using the yoda pull command.
