### ISSUE TITLE
I want to be able to compare my .yoda file to the versions of others

### ISSUE THREAD

**Issue by jklewa** [kcmerrill/yoda#9]
I would be helpful to see of all the people sharing a project with me who is sharing the same version and who is sharing a different version.

If i want to compare my version to another persons version a diff would be helpful

**Comment by kcmerrill** [comment]
Woot! Added. Anywhere within a subdirectory of your project, you can now do yoda diff user/project and get a diff. 

Also, I ended up using a php module to do it so no cmd line dependancies. Let me know what you think.
-kc
